# Generated by Django 2.1.7 on 2019-05-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('users', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remote_id',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='remote id'
            ),
        )
    ]
