language: python
python:
  - "3.6"

before_install:
  - python -V
  - rm -rf psycopg2

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

env:
  - DATABASE_URL=postgresql://postgres@localhost/travisci DJANGO_SETTINGS_MODULE=app.settings.test SECRET_KEY=insecure

script:
  - flake8
  - black --check .
  - pytest
  
services:
  - postgresql
