language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
env:
  - DATABASE_URL=postgresql://postgres@localhost/travisci DJANGO_SETTINGS_MODULE=app.settings.test
script:
  - flake8
  - black --check .
  - pytest
services:
  - postgresql
